### ISSUE TITLE
可以把这个文档制作为  deb 包吗？

### ISSUE THREAD

**Issue by atzlinux** [hosiet/talk-debian-2020#1]
这个文档挺不错的。能够让更多的中国人了解 Debian，参与贡献 Debian。

如果能够制作为 deb 包，就可以默认加入 apt 软件源，甚至默认在发行版里面集成该文档。

**Comment by hosiet** [comment]
我个人不认为这份文档有足够的价值和质量足以整合进 Linux 发行版中。当然，因为文档是 CC-BY 4.0 授权属于自由文档且构建工具链广泛可用（只需要 texlive），其他人可以依照许可证自由使用或对文档进行整合和打包。
